### PR TITLE
Ui/dashboard

### PR DESCRIPTION
**Pull request by thebeyondr**

### CODE REVIEW

**Comment by tkmct** [comment]
@thebeyondr Can you add storybook related packages to the root dir?

**Comment by thebeyondr** [comment]
Lol sure. Put tailwindcss at root level too? (It's also in ui atm)

**Comment by tkmct** [comment]
Yes, let's put all packages in root and remove package.json and package-lock from ui🙏

**Comment by thebeyondr** [comment]
> Yes, let's put all packages in root and remove package.json and package-lock from ui🙏

good, already did that!

**Comment by thebeyondr** [comment]
Forked and made PR #31  instead

**Pull request closed without merging**
