### PR TITLE
NFT List Section

### LINKED ISSUE #42: [storybook] NFT list section
add NFT list section to overview page

### PR DESCRIPTION
**Pull request by thebeyondr**
Closes #42

### CODE REVIEW

**Comment by thebeyondr** [comment]
| image |
| :--: |
| @tkmct I changed up the design. It will be a dropdown now. Click a collection and the NFTs show up. |

Thoughts?

**Comment by thebeyondr** [comment]
@tkmct spent most of today tweaking and setting up an `Accordion` component only to remember that `headlessui` has a `Disclosure` component that does it lol 🙃

 It doesn't work in story book anymore since it expects actual data that doesn't exist. However, I think the UI is ready for your touch now.

**Comment by tkmct** [comment]
@thebeyondr ah, it happens😅
Thank you for that.

**Comment by thebeyondr** [comment]
### 💾 Sample data hooked up

image

Questions @tkmct --
1. Is there an easy way to get the logos for NFT collections?
2. I noticed your sample data has `moralis` in it.. are we using Moralis' API? 
2. Any idea how you'd like me to resolve the `ipfs://` image links?

**Comment by thebeyondr** [comment]
| image |
| -- |
| *Modal that displays the clicked NFT's detail* |

**Comment by thebeyondr** [comment]
@tkmct Just checked and that's actually all done already lol

**Review by tkmct — APPROVED** [review]
lgtm!

**Pull request merged**
